DROP DATABASE IF EXISTS guessGameDB;
CREATE DATABASE guessGameDB;

USE guessGameDB;

CREATE TABLE game(
id INT PRIMARY KEY AUTO_INCREMENT,
answer SMALLINT(4) NOT NULL,
finished BOOLEAN DEFAULT false NOT NULL);

CREATE TABLE round(
id INT PRIMARY KEY AUTO_INCREMENT,
time DATETIME NOT NULL,
guess SMALLINT(4) NOT NULL,
result VARCHAR(30) NOT NULL,
gameId INT NOT NULL,
FOREIGN KEY (gameId) REFERENCES game(id));

DROP DATABASE IF EXISTS guessGameDBtest;
CREATE DATABASE guessGameDBtest;

USE guessGameDBtest;

CREATE TABLE game(
	id 			INT 		PRIMARY KEY AUTO_INCREMENT,
	answer 		SMALLINT(4) NOT NULL,
	finished 	BOOLEAN 	DEFAULT false NOT NULL
);

CREATE TABLE round(
	id 		INT 			PRIMARY KEY AUTO_INCREMENT,
	time 	DATETIME 		NOT NULL,
	guess 	SMALLINT(4) 	NOT NULL,
	result 	VARCHAR(30) 	NOT NULL,
	gameId 	INT 			NOT NULL,
	
	FOREIGN KEY (gameId) 	REFERENCES game(id)
);

